// Autogenerated from Pigeon (v25.3.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")


import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object MoniepointCheckoutPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

enum class CheckoutEnvironment(val raw: Int) {
  SANDBOX(0),
  PRODUCTION(1);

  companion object {
    fun ofRaw(raw: Int): CheckoutEnvironment? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}
private open class MoniepointCheckoutPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          CheckoutEnvironment.ofRaw(it.toInt())
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is CheckoutEnvironment -> {
        stream.write(129)
        writeValue(stream, value.raw)
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface MoniepointCheckout {
  fun initialize(publicKey: String, environment: CheckoutEnvironment)
  fun tokenize(callback: (Result<String>) -> Unit)

  companion object {
    /** The codec used by MoniepointCheckout. */
    val codec: MessageCodec<Any?> by lazy {
      MoniepointCheckoutPigeonCodec()
    }
    /** Sets up an instance of `MoniepointCheckout` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: MoniepointCheckout?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.moniepoint_checkout.MoniepointCheckout.initialize$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val publicKeyArg = args[0] as String
            val environmentArg = args[1] as CheckoutEnvironment
            val wrapped: List<Any?> = try {
              api.initialize(publicKeyArg, environmentArg)
              listOf(null)
            } catch (exception: Throwable) {
              MoniepointCheckoutPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.moniepoint_checkout.MoniepointCheckout.tokenize$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.tokenize{ result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MoniepointCheckoutPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MoniepointCheckoutPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
